spring.application.name=bookHub
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=bookHub;encrypt=false
spring.datasource.username=sa
spring.datasource.password=Pa$$w0rd

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect